import { notFound } from 'next/navigation'
import Link from 'next/link'

const pages: Record<string, { eyebrow: string; title: string; intro: string; sections: { title: string; body: string }[] }> = {
  contact: { eyebrow: 'Client services', title: 'Let’s talk', intro: 'Our client care team is here to help with orders, sizing and product questions.', sections: [{title:'Email',body:'hello@notjustdark.com — we aim to reply within one business day.'},{title:'Studio hours',body:'Monday–Saturday, 10:00–18:00 IST.'}] },
  shipping: { eyebrow: 'Delivery', title: 'Shipping information', intro: 'Every order is prepared with care and tracked from our studio to your door.', sections: [{title:'India',body:'Complimentary standard delivery on orders over ₹5,000. Most orders arrive in 3–7 business days.'},{title:'Tracking',body:'Tracking details are shared once your order leaves our studio.'}] },
  returns: { eyebrow: 'Client care', title: 'Returns & exchanges', intro: 'We want every piece to feel considered and right.', sections: [{title:'Return window',body:'Request a return within 14 days of delivery. Pieces must be unworn, unwashed and retain their original tags.'},{title:'Final sale',body:'Personalised pieces and final-sale items cannot be returned unless faulty.'}] },
  faq: { eyebrow: 'Answers', title: 'Frequently asked', intro: 'A concise guide to ordering from NOT JUST DARK.', sections: [{title:'Can I change an order?',body:'Contact us promptly. We can make changes before fulfilment begins.'},{title:'How do I care for a piece?',body:'Follow the garment care label and store pieces away from direct sunlight.'},{title:'Are payments secure?',body:'Payments are processed through Razorpay; card details are not stored by us.'}] },
  'size-guide': { eyebrow: 'The right fit', title: 'Size guide', intro: 'Our silhouettes vary from precise tailoring to intentionally relaxed proportions.', sections: [{title:'How to measure',body:'Measure chest, waist and hip close to the body without pulling the tape tight.'},{title:'Between sizes?',body:'Choose the larger size for a relaxed fit, or contact client care for garment-specific measurements.'}] },
  sustainability: { eyebrow: 'Made with intent', title: 'Our responsibility', intro: 'We favour considered production, durable construction and pieces designed to remain in rotation.', sections: [{title:'Small runs',body:'Limited production helps us avoid excess inventory and preserve the individuality of each collection.'},{title:'Longer life',body:'Care guidance and thoughtful construction help every piece live beyond a single season.'}] },
  careers: { eyebrow: 'Join the studio', title: 'Careers', intro: 'We are building a team that sees fashion as culture, craft and clear point of view.', sections: [{title:'Open applications',body:'Send a short introduction and portfolio to careers@notjustdark.com.'}] },
  press: { eyebrow: 'Press room', title: 'Notes & features', intro: 'For editorial requests, samples and brand assets, contact our press desk.', sections: [{title:'Press enquiries',body:'press@notjustdark.com'}] },
  privacy: { eyebrow: 'Legal', title: 'Privacy policy', intro: 'We collect only the information needed to provide your account, orders and client care.', sections: [{title:'Your information',body:'Account, delivery and payment-reference data is used to fulfil orders and secure the service.'},{title:'Your choices',body:'You may request access, correction or deletion of eligible personal data by contacting us.'}] },
  terms: { eyebrow: 'Legal', title: 'Terms of service', intro: 'By using this store, you agree to provide accurate information and use the service lawfully.', sections: [{title:'Orders',body:'Orders are accepted once payment is confirmed. We may cancel and refund an order when stock or pricing is incorrect.'},{title:'Content',body:'Brand imagery, copy and design remain the property of NOT JUST DARK.'}] },
  cookies: { eyebrow: 'Legal', title: 'Cookie policy', intro: 'We use essential browser storage for sign-in, carts and preferences.', sections: [{title:'Essential storage',body:'Session and authentication data is required for the store to function.'},{title:'Control',body:'You can clear browser storage in your browser settings; doing so may sign you out and reset your cart.'}] },
}

export function generateStaticParams() { return Object.keys(pages).map(info => ({ info })) }

export default function InfoPage({ params }: { params: { info: string } }) {
  const page = pages[params.info]
  if (!page) notFound()
  return <div className="min-h-screen bg-cream-50 pt-32 pb-24"><div className="container mx-auto px-4 max-w-5xl"><p className="text-luxury-caps text-noir-400 mb-5 animate-fade-in">{page.eyebrow}</p><h1 className="font-display text-6xl lg:text-8xl max-w-4xl animate-fade-in-up">{page.title}</h1><p className="mt-10 text-xl lg:text-2xl font-light leading-relaxed max-w-3xl text-noir-600">{page.intro}</p><div className="mt-20 grid md:grid-cols-2 gap-x-16 gap-y-12 border-t border-noir-950/15 pt-10">{page.sections.map(section => <section key={section.title}><p className="text-luxury-caps text-noir-400 mb-4">{section.title}</p><p className="text-noir-600">{section.body}</p></section>)}</div><Link href="/" className="link-editorial inline-block mt-20 text-sm">Return home</Link></div></div>
}
